"""
Defines url enpoints and their handlers
"""
from django.urls import path
from .views import *

urlpatterns = [
    path(
            "businesses/",
            business_list
    ),
    path(
            "businesses/<business_id>/",
            business_details
    ),
    path(
            "businesses/<business_id>/hours/",
            business_hour_list
    ),
    path(
            "businesses/<business_id>/hours/<hour_id>/",
            business_hour_details
    ),
    path(
            "businesses/<business_id>/images/",
            business_image_list
    ),
    path(
            "businesses/<business_id>/images/<image_id>/",
            business_image_details
    ),
    path(
            "businesses/<business_id>/favorites/",
            business_favorite_list
    ),
    path(
            "businesses/<business_id>/favorites/<favorite_id>/",
            business_favorite_details
    ),
    path(
            "businesses/<business_id>/reviews/",
            business_review_list
    ),
    path(
            "businesses/<business_id>/reviews/<review_id>/",
            business_review_details
    ),
    path(
            "businesses/<business_id>/products/",
            product_list
    ),
    path(
            "businesses/<business_id>/products/<product_id>/",
            product_details
    ),
    path(
            "businesses/<business_id>/products/<product_id>/images/",
            product_image_list
    ),
    path(
            "businesses/<business_id>/products/<product_id>/"
            "images/<image_id>/",
            product_image_details
    ),
    path(
            "businesses/<business_id>/products/<product_id>/favorites/",
            product_favorite_list
    ),
    path(
            "businesses/<business_id>/products/<product_id>/"
            "favorites/<favorite_id>/",
            product_favorite_details
    ),
    path(
            "businesses/<business_id>/products/<product_id>/reviews/",
            product_review_list
    ),
    path(
            "businesses/<business_id>/products/<product_id>/"
            "reviews/<review_id>/",
            product_review_details
    ),
    path(
            "users/<user_id>/notifications/",
            user_notification_list
    ),
    path(
            "users/<user_id>/notifications/<user_notification_id>/",
            user_notification_details
    ),
    path(
            "users/<user_id>/favorites/products",
            user_favorite_product_list

    ),
    path(
            "users/<user_id>/favorites/businesses",
            user_favorite_business_list

    ),
    path(
            "ratings/",
            project_ratings

    ),
]
