FROM python:3

WORKDIR /usr/src/business

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN python manage.py makemigrations api && python manage.py migrate

EXPOSE 8000

CMD [ "python", "manage.py", "runserver" ]
